version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/src/bosh_release"
    schedule:
      interval: "daily"

# Do we want to autoupdate go-modules in /src ?
# Do we want to autoupdate /dockerfiles ?
