#!/bin/bash

set -x -e

version=`cat smb-volume-version/number`
tarball_name=smb-volume-$version.tgz

pushd smb-volume-release
  bosh -n create-release --version=$version --force --tarball=$tarball_name
  mv $tarball_name ../created-smb-volume-release
popd
