#!/bin/bash

set -x -e

version=`cat smb-volume-version/number`
pushd smb-volume-release

rm -rf .final_builds

bosh -n create-release --tarball=dev_releases/smb-volume/smb-volume-$version.tgz --version $version --name smb-volume --force

mv dev_releases/smb-volume/smb-volume-$version.tgz ../created-smb-volume-release/smbvolume-$version.tgz
popd
