#!/bin/bash

set -x -e

version=`cat smb-volume-version/number`
pushd smb-volume-release

rm -rf .final_builds

bosh -n --parallel 10 create release --version $version --name smb-volume --force --with-tarball
mv dev_releases/smb-volume/smb-volume-$version.tgz ../created-smb-volume-release/smbvolume-$version.tgz
popd
