#!/bin/bash

set -x -e

function finish {
  pkill ssh || true
}
trap finish EXIT

apt-get update
apt-get -y install cifs-utils realpath

pushd smb-volume-release
  export GOROOT=/usr/local/go
  export PATH="${GOROOT}/bin:${PATH}"

  export GOPATH="${PWD}"
  export PATH="${PWD}/bin:${PATH}"

  export SMB_RELEASE_DIR="${PWD}"

  go get github.com/onsi/ginkgo/ginkgo
  go get github.com/onsi/gomega

  listen_port=8589
  listen_address="0.0.0.0:${listen_port}"
  driver_address="http://${listen_address}"

  mkdir -p ~/voldriver_plugins
  drivers_path="$(realpath ~/voldriver_plugins)"

  mkdir -p "${SMB_RELEASE_DIR}/tmp"

  export FIXTURE_FILENAME="${SMB_RELEASE_DIR}/tmp/fixture.json"

  echo "{
    \"volman_driver_path\": \"~/voldriver_plugins\",
    \"driver_address\": \"${driver_address}\",
    \"driver_name\": \"smbdriver\",
    \"create_config\": {
      \"Name\": \"smb-volume-name\",
      \"Opts\": {\"source\":\"${SMB_REMOTE_PATH}\",\"username\":\"${SMB_USERNAME}\",\"password\":\"${SMB_PASSWORD}\"}
    }
  } " > "${FIXTURE_FILENAME}"

  pushd src/code.cloudfoundry.org/smbdriver
    go build -o "${SMB_RELEASE_DIR}/tmp/smbdriver" "cmd/smbdriver/main.go"
  popd

  go get -t code.cloudfoundry.org/docker_driver_integration_tests

  pkill smbdriver || true

  mountDir="${SMB_RELEASE_DIR}/tmp/mountdir"
  mkdir -p "${mountDir}"

  "${SMB_RELEASE_DIR}/tmp/smbdriver" -listenPort="${listen_port}" -transport="tcp" -driversPath="${drivers_path}" \
        --mountDir="${mountDir}" \
        --mountFlagAllowed="username,password,file_mode,dir_mode,readonly,domain,vers,sec" \
        --mountFlagDefault="" &

  ginkgo -v -keepGoing "src/code.cloudfoundry.org/${TEST_PACKAGE}" -race

  pkill smbdriver || true

  rm -rf "${SMB_RELEASE_DIR}/tmp"
popd
