#!/bin/bash

set -x -e

sed -i 's/main $@//' /usr/local/bin/start-bosh
source /usr/local/bin/start-bosh
export certs_dir=$(mktemp -d)
export OUTER_CONTAINER_IP=$(ruby -rsocket -e 'puts Socket.ip_address_list
                          .reject { |addr| !addr.ip? || addr.ipv4_loopback? || addr.ipv6? }
                          .map { |addr| addr.ip_address }')

export DOCKER_HOST="tcp://${OUTER_CONTAINER_IP}:4243"

start_docker "${certs_dir}"

docker --tlsverify --tlscacert=${certs_dir}/ca.pem --tlscert=${certs_dir}/cert.pem --tlskey=${certs_dir}/key.pem \
            run -it -p 139:139 -p 445:445 -d dperson/samba -p \
            -u "example1;badpass" \
            -s "example1;/example1;no;no;no;example1" \
            -p \
            -S

apt-get update
apt-get -y install cifs-utils realpath

pushd smb-volume-release
  export GOROOT=/usr/local/go
  export PATH="${GOROOT}/bin:${PATH}"

  export GOPATH="${PWD}"
  export PATH="${PWD}/bin:${PATH}"

  export SMB_RELEASE_DIR="${PWD}"

  go get github.com/onsi/ginkgo/ginkgo
  go get github.com/onsi/gomega

  listen_port=8589
  listen_address="0.0.0.0:${listen_port}"
  driver_address="http://${listen_address}"

  mkdir -p ~/voldriver_plugins
  drivers_path="$(realpath ~/voldriver_plugins)"

  mkdir -p "${SMB_RELEASE_DIR}/tmp"

  export FIXTURE_FILENAME="${SMB_RELEASE_DIR}/tmp/fixture.json"

  echo "{
    \"volman_driver_path\": \"~/voldriver_plugins\",
    \"driver_address\": \"${driver_address}\",
    \"driver_name\": \"smbdriver\",
    \"create_config\": {
      \"Name\": \"smb-volume-name\",
      \"Opts\": {\"source\":\"${SMB_REMOTE_PATH}\",\"username\":\"${SMB_USERNAME}\",\"password\":\"${SMB_PASSWORD}\"}
    }
  } " > "${FIXTURE_FILENAME}"

  pushd src/code.cloudfoundry.org/smbdriver
    go build -o "${SMB_RELEASE_DIR}/tmp/smbdriver" "cmd/smbdriver/main.go"
  popd

  mkdir -p src/code.cloudfoundry.org/docker_driver_integration_tests
  cp -R ../docker_driver_integration_tests/* src/code.cloudfoundry.org/docker_driver_integration_tests

  mountDir="${SMB_RELEASE_DIR}/tmp/mountdir"
  mkdir -p "${mountDir}"

  export DRIVER_CMD="${SMB_RELEASE_DIR}/tmp/smbdriver"
  export DRIVER_OPTS="-listenPort="${listen_port}",-transport="tcp",-driversPath="${drivers_path}",--mountDir="${mountDir}""

  ginkgo -v -keepGoing "src/code.cloudfoundry.org/${TEST_PACKAGE}" -race

  rm -rf "${SMB_RELEASE_DIR}/tmp"
popd
