#!/bin/bash

set -x -e

apt-get -y install cifs-utils

source bosh-env/set-env.sh
smbtestserver_ip=$(bosh -d smbtestserver instances|grep smbtestserver|awk '{print $4}')

pushd smb-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH
    export SOURCE=//${smbtestserver_ip}/vol1

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-driver-cert-tests -race
popd
