#!/bin/bash

set -e -x

pushd src/github.com/AbelHu/azurefilebroker
  go get github.com/tools/godep

  godep get .
  pushd azurefilebroker
    godep get .
  popd

  mkdir -p bin
  GOOS=linux GOARCH=amd64 go build -o bin/azurefilebroker
popd
