#!/bin/bash

set -e -x

pushd src/code.cloudfoundry.org/smbdriver > /dev/null
  go get github.com/onsi/ginkgo/ginkgo
  go get github.com/onsi/gomega
  go get -t .
  pushd cmd/smbdriver > /dev/null
    go get -t .
  popd > /dev/null
  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress "$@"
popd > /dev/null
