#!/bin/bash

set -e -x

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

listen_port=8589
listen_address=0.0.0.0:${listen_port}
driver_address=http://${listen_address}

mkdir -p ~/voldriver_plugins
drivers_path=$(realpath ~/voldriver_plugins)

mkdir -p $SMB_RELEASE_DIR/tmp

echo "{
  \"volman_driver_path\": \"~/voldriver_plugins\",
  \"driver_address\": \"${driver_address}\",
  \"driver_name\": \"smbdriver\",
  \"create_config\": {
    \"Name\": \"smb-volume-name\",
    \"Opts\": {\"source\":\"${SOURCE}\",\"uid\":\"2000\",\"gid\":\"2000\",\"username\":\"${username}\",\"password\":\"${password}\"}
  }
} "  > $SMB_RELEASE_DIR/tmp/fixture.json

export FIXTURE_FILENAME="$SMB_RELEASE_DIR/tmp/fixture.json"

cd `dirname $0`
cd ../src/github.com/cloudfoundry/smbdriver

go build -o "$SMB_RELEASE_DIR/tmp/smbdriver" "cmd/smbdriver/main.go"

go get -t code.cloudfoundry.org/volume_driver_cert

killall -9 smbdriver || true

mountDir=${SMB_RELEASE_DIR}/tmp/mountdir
mkdir -p ${mountDir}

$SMB_RELEASE_DIR/tmp/smbdriver -listenPort="${listen_port}" -transport="tcp" -driversPath="${drivers_path}" \
      --mountDir=${mountDir}  \
      --mountFlagAllowed="username,password,uid,gid,file_mode,dir_mode,readonly,domain,vers,sec" \
      --mountFlagDefault="uid:2000,gid:2000" &

pushd $SMB_RELEASE_DIR
    ginkgo -v -keepGoing src/code.cloudfoundry.org/volume_driver_cert
popd

killall -9 smbdriver || true

rm -f $SMB_RELEASE_DIR/tmp/nfsv3driver
